version: '3.7'

networks:
  starcom: {}

services:
  sat0:
    build: .
    container_name: status
    ports:
    - "5001:5001"
    networks:
      - starcom
    restart: unless-stopped
  sat0:
    build: sat0_broken_webserver/
    container_name: sat0
    ports:
    - "80:80"
    - "22:22"
    networks:
      - starcom
    restart: unless-stopped
    depends_on:
    - status
  sat1:
    build: sat1_reverse_engineering/
    container_name: sat1
    networks:
      - starcom
    restart: unless-stopped
    depends_on:
    - status
  sat2:
    build: sat2_brute_force/
    container_name: sat2
    ports:
    - "5022:5022"
    networks:
      - starcom
    restart: unless-stopped
    depends_on:
    - status
