version: '3.7'

networks:
  starcom:

services:
  status:
    build: status_server/
    container_name: status
    ports:
    - "5001:5001"
    networks:
      - starcom
    restart: unless-stopped
  sat0:
    build: sat0_broken_webserver/
    container_name: sat0
    ports:
    - "8000:8000"
    - "1022:22"
    networks:
      - starcom
    restart: unless-stopped
    depends_on:
    - status
  sat1:
    build: sat1_reverse_engineering/
    container_name: sat1
    ports:
    - "7777:7777"
    networks:
      - starcom
    restart: unless-stopped
    depends_on:
    - status
  sat2:
    build: sat2_brute_force/
    container_name: sat2
    ports:
    - "5022:22"
    networks:
      - starcom
    restart: unless-stopped
    depends_on:
    - status
